/*
 * IdentityPreferencesPanel.java Created on February 10, 2011, 10:02 AM
 */

package multiplicity3.config.identity;

import java.awt.Rectangle;
import java.util.UUID;

/**
 * @author dcs0ah1
 */
public class IdentityConfigPanel extends javax.swing.JPanel
{
	/**
	 *
	 */
	private static final long serialVersionUID = -1239665300555242025L;

	// Variables declaration - do not modify//GEN-BEGIN:variables
	/** The j button1. */
	private javax.swing.JButton jButton1;

	/** The j label1. */
	private javax.swing.JLabel jLabel1;

	/** The prefs. */
	private IdentityConfigPrefsItem prefs;

	/** The txt id. */
	private java.awt.TextField txtID;

	// End of variables declaration//GEN-END:variables

	/** Creates new form IdentityPreferencesPanel */
	public IdentityConfigPanel()
	{
		this.prefs = new IdentityConfigPrefsItem();
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents()
	{

		txtID = new java.awt.TextField();
		jLabel1 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();

		txtID.setText(prefs.getID());
		txtID.addKeyListener(new java.awt.event.KeyAdapter()
		{
			@Override
			public void keyReleased(java.awt.event.KeyEvent evt)
			{
				txtIDKeyReleased(evt);
			}
		});

		jLabel1.setText("Unique ID:");

		jButton1.setText("Generate ID");
		jButton1.addActionListener(new java.awt.event.ActionListener()
		{
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				jButton1ActionPerformed(evt);
			}
		});

		setLayout(null);

		jLabel1.setBounds(new Rectangle(30, 30, 100, 24));
		txtID.setBounds(new Rectangle(130, 30, 300, 24));
		jButton1.setBounds(new Rectangle(130, 60, 140, 24));

		add(jLabel1);
		add(txtID);
		add(jButton1);

	}// </editor-fold>//GEN-END:initComponents

	/**
	 * J button1 action performed.
	 *
	 * @param evt
	 *            the evt
	 */
	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_jButton1ActionPerformed
		txtID.setText(UUID.randomUUID().toString());
		prefs.setID(txtID.getText());
	}// GEN-LAST:event_jButton1ActionPerformed

	/**
	 * Txt id key released.
	 *
	 * @param evt
	 *            the evt
	 */
	private void txtIDKeyReleased(java.awt.event.KeyEvent evt)
	{// GEN-FIRST:event_txtIDKeyReleased
		prefs.setID(txtID.getText());
	}// GEN-LAST:event_txtIDKeyReleased

}
